version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - run:
          name: Install SSH & rsync
          command: |
            sudo apt-get update
            sudo apt-get install -y openssh-client rsync

      - add_ssh_keys:
          fingerprints:
            - "SHA256:UhIo1a/GjPwET/jeu3RVCY/idJO+uCcAkkyMab/3kMo" 

      - run:
          name: Deploy HTML files to EC2
          command: |
            rsync -avz --delete ./ \
              -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
              $SSH_USER@$HOST:/var/www/dml-language.org \
              --exclude ".git" \
              --exclude ".circleci"

      - run:
          name: Set permissions on EC2
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$HOST \
              "sudo chown -R www-data:www-data /var/www/dml-language.org && sudo chmod -R 755 /var/www/dml-language.org"

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
