name: Deploy Static Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy static files to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        source: "./"
        target: "/var/www/laravel/public/custom-frontend"
        strip_components: 0
        rm: true  # Usuwa stare pliki w folderze target

    - name: Set correct permissions (optional)
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          sudo chown -R www-data:www-data /var/www/laravel/public/custom-frontend
          sudo chmod -R 755 /var/www/
