version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - run:
          name: Zainstaluj narzędzia SSH i rsync
          command: |
            sudo apt-get update
            sudo apt-get install -y openssh-client rsync

      - add_ssh_keys:
          fingerprints:
            - "SHA256:YOUR_SSH_KEY_FINGERPRINT"

      - run:
          name: Wdróż pliki do EC2
          command: |
            rsync -avz --delete ./ \
              $USER@$HOST:/var/www/ \
              --exclude ".git" \
              --exclude ".circleci"

      - run:
          name: Ustaw prawa dostępu
          command: |
            ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
              sudo chown -R www-data:www-data /var/www/
              sudo chmod -R 755 /var/www/
            EOF

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy
