version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y openssh-client rsync

      - add_ssh_keys:
          fingerprints:
            - "SHA256:YOUR_SSH_KEY_FINGERPRINT"

      - run:
          name: Deploy to server
          command: |
            rsync -avz --delete ./ \
              $SSH_USER@$HOST:/var/www/ \
              --exclude ".git" \
              --exclude ".circleci"

      - run:
          name: Set permissions
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$HOST \
              "sudo chown -R www-data:www-data /var/www/ && sudo chmod -R 755 /var/www/"

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
