version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y openssh-client rsync

      - add_ssh_keys:
          fingerprints:
            - "SHA256:UhIo1a/GjPwET/jeu3RVCY/idJO+uCcAkkyMab/3kMo"

      - run:
          name: Deploy to server via rsync
          command:
            rsync -avz --delete ./ \
              -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \ 
